#!/bin/bash

RDP=${REDIS_DATA_PATH:=/tmp/rkta-redis-data}
MDP=${MONGO_DATA_PATH:=/tmp/rkta-mongo-data}

mkdir -pv $MDP
mkdir -pv $RDP

export REDIS_DATA_PATH;
export MONGO_DATA_PATH;

cd `dirname "${BASH_SOURCE[0]}"`

convox start -f ./convox/docker-compose.yml
